# simple github-actions workflow
# to run on schedule
# on:
#  schedule:
#   - cron: '*/5 * * * *' -> every 5 minutes

name: selenium test project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Lint With Flake8
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Run Tests
        run:
          pytest